# pylint: disable=too-many-lines
"""This contains a list of table columns to use for each table in the data set."""

table_keys = {  # This table contains the keys used in the database to identify each entry.
    "Aftaleindhold":                ["Aftaleindhold"],
    "BO-aftale-haendelse":          ["Ekstern_reference_nøgle"],
    "BO-aftale":                    ["Aftalenummer", "Bilagsnummer", "Position"],
    "Bilag-lukket":                 ["Dato-ID", "Identifikation", "Intervalnummer", "Recordnummer"],
    "Bilag-master":                 ["Bilagsnummer", "Gentagelsesposition", "Position", "Delposition"],
    "Forretningspartner":           ["Klient", "Forretningspartner", "Identifikationsart", "Forretningspartner-GUID"],  # These were removed as they often contain CPRs: "Identifikationsnr.", 
    "Indbetalinger":                ["Art_kilde", "Betalingsidentifikator", "Løbenummer"],
    "Opsaetning-Aftalekontotype":   ["Klient", "Sprognøgle", "Aftalekontotype"],
    "Opsaetning-Rykkerniveau":      ["Sprognøgle", "Rykkeprocedure", "Rykkeniveau"],
    "RIM-aftale-renter":            ["Aftalenummer", "Intr-posnr"],
    "Rykker":                       ["Dato-ID", "Identifikation", "Forretningspartner", "Aftalekonto", "Rykkertæller", "Bilagsnummer", "Gentagelsesposition", "Position", "Delposition"],
    "UU-aftale-haefter":            ["Klient", "Aftalenummer", "Forretningspartner"],
    "FP-aftale":                    None,
    "RIM-aftale-rater":             None,
    "RIM-aftale":                   None,
    "Bilag-aaben":                  None,
    "UU-aftale":                    None,
}

table_date_columns = {  # This table contains the date columns, that are used to define when they were added, for filtering on a date range.
    "BO-aftale-haendelse":          ["Afskrivnings_dato", "Betalingsdato"],
    "FP-aftale":                    "Oprettet_den",
    "Indbetalinger":                "Oprettet_den",
    "RIM-aftale-rater":             "Oprettet_den",
    "RIM-aftale-renter":            "Oprettet_den",
    "RIM-aftale":                   "Oprettet_den",
    "Rykker":                       "Udstedelsesdato",
    "Bilag-aaben":                  "Bogføringsdato",
    "Bilag-lukket":                 "Bogføringsdato",
    "Bilag-master":                 "Registreringsdato",
    "BO-aftale":                    None,
    "Forretningspartner":           None,
    "Opsaetning-Aftalekontotype":   None,
    "Opsaetning-Rykkerniveau":      None,
    "UU-aftale-haefter":            None,
    "UU-aftale":                    None,
}

table_used_columns = {  # This table defines all the columns we actually use from each table.
    "Aftaleindhold": [
        "Aftaleindhold",
        "Oprettet_af",
        "Oprettet_den",
        "Ændret_af",
        "Ændret_den",
        "Indholdsart",
        "Bet._aftaleindhold",
        "Nummer_i_basissystem",
        "Kommune_kode"
    ],

    "BO-aftale-haendelse": [
        "Afskrevet",
        "Afskrivnings_dato",
        "Aftalenummer",
        "Beløb",
        "Betalingsdato",
        "Bobehandling",
        "Ekstern_reference_nøgle",
        "Indbetalt_af_bobestyrer",
        "Klient",
        "Kommune_kode",
        "Korrespondanceart",
        "Printdato",
        "Udtrækstype",
        "Valuta",
    ],

    "BO-aftale": [
        "Ændringer_efter_første_anmeld",
        "Afskrevet",
        "Aftale",
        "Aftalekonto",
        "Aftalenummer",
        "Aftalestatus",
        "Aftaletype",
        "Bilagsnummer",
        "Bobehandling",
        "Deltransaktion",
        "Fjernet",
        "Første_anmeldelse",
        "Hovedtransaktion",
        "Indbetalt_af_bobestyrer",
        "Indholdsart",
        "Kommune_kode",
        "Oprettet_beløb",
        "Position",
        "Restbeløb",
        "Valuta",
    ],

    "Bilag-aaben": [
        "Aftaleindhold",
        "Aftalekonto",
        "Aftalekontotype",
        "Aftalenummer",
        "Aftalestatus",
        "Aftaletype",
        "Antal_poster",
        "Beløb",
        "Beløb_intern_valuta",
        "BevillAnsvarssted",
        "Bevillingsposition",
        "Bevillingsprogram",
        "Bilagsdato",
        "Bilagsnummer",
        "Bogføringsdato",
        "Dato-ID",
        "Deltransaktion",
        "Firmakode",
        "Forretningspartner",
        "Funktionsområde",
        "Henstand_til",
        "Hovedtransaktion",
        "Identifikation",
        "Indholdsart",
        "Kapitalmidler",
        "Klient",
        "Kommune_kode",
        "Kredit_oprindelses_dato",
        "Landenøgle",
        "Nettoforfald",
        "Original-FI-område",
        "Periodenøgle",
        "Position",
        "Positionstekst",
        "Postnummer",
        "Referencebilagsnr.",
        "Registreringsdato",
        "Rykkeniveau",
        "Rykkeniveautype",
        "Rykkeprocedure",
        "Rykkeproceduretype",
        "SBS_dokumentnummer",
        "Skæringsdato",
        "Sorteringsbetegnelse",
        "Statistiknøgle",
        "Udligning_kredit_oprindelse",
        "Udligningsstatus",
        "Valuta"
    ],

    "Bilag-lukket": [
        "Afskrivningsårsag",
        "Afskrivningsdato",
        "Aftaleindhold",
        "Aftalekonto",
        "Aftalekontotype",
        "Aftalenummer",
        "Aftalestatus",
        "Aftaletype",
        "Antal_poster",
        "Bankafregningskonto",
        "Beløb",
        "Beløb_intern_valuta",
        "BevillAnsvarssted",
        "Bevillingsposition",
        "Bevillingsprogram",
        "Bilagsdato",
        "Bilagsnummer",
        "Bilagstype_markering",
        "BogfDato_udligning",
        "Bogføringsdato",
        "Bortposteringsårsag",
        "Dato-ID",
        "Deltransaktion",
        "Firmakode",
        "Forretningspartner",
        "Fra",
        "Funktionsområde",
        "Henstand_til",
        "Hovedtransaktion",
        "Identifikation",
        "Indbetalingstype",
        "Indholdsart",
        "Intervalnummer",
        "Kapitalmidler",
        "Klient",
        "Kommune_kode",
        "Kredit_oprindelses_dato",
        "Landenøgle",
        "Nettoforfald",
        "Original-FI-område",
        "Position",
        "Postnummer",
        "Recordnummer",
        "Referencebilagsnr.",
        "Registreringsdato",
        "Rykkeniveau",
        "Rykkeprocedure",
        "SBS_dokumentnummer",
        "Sorteringsbetegnelse",
        "Statistiknøgle",
        "Til",
        "Tilbageført_via",
        "Udligning",
        "Udligning_kredit_oprindelse",
        "Udligningsårsag",
        "Udligningsbeløb",
        "Udligningsbilag",
        "Udligningsdato",
        "Udligningsstatus",
        "Udligningsvaluta",
        "Underapplikation",
        "Valørdato_udligning",
        "Valuta"
    ],

    "Bilag-master": [
        "AfregnPeriode_fra",
        "AfregnPeriode_til",
        "Afskrivningsårsag",
        "Aftale",
        "Aftalekonto",
        "Aftalekontotype",
        "Aftalenummer",
        "Aftalestatus",
        "Aftaletype",
        "Applikationsområde",
        "Artskonto",
        "Beløb",
        "Beløb_intern_valuta",
        "Betalingsordre",
        "Bilagsart",
        "Bilagsdato",
        "Bilagsnummer",
        "Bilagstype_markering",
        "BogfDato_udligning",
        "Bogføringsdato",
        "Bortposteringsårsag",
        "Delposition",
        "Deltransaktion",
        "Firmakode",
        "Forretningspartner",
        "Gentagelsesposition",
        "Henstand_til",
        "Hovedtransaktion",
        "Indholdsart",
        "Kommune_kode",
        "KontofastsætKendet.",
        "Momsindikator",
        "Nettoforfald",
        "Oprindelse",
        "Position",
        "Referencebilagsnr.",
        "Referencenøgle",
        "Referenceoperation",
        "Registreringsdato",
        "Rentenøgle",
        "Rykkeprocedure",
        "SBS_dokumentnummer",
        "Skæringsdato",
        "Statistiknøgle",
        "Tilbageført_via",
        "Udligngningstype",
        "Udligningsårsag",
        "Udligningsbeløb",
        "Udligningsbilag",
        "Udligningsdato",
        "Udligningsstatus",
        "Udligningsvaluta",
        "Valørdato_udligning",
        "Valuta",
    ],

    "FP-aftale": [
        "AA_type",
        "Ændret_den",
        "Aftale",
        "Aftalekonto",
        "Aftalenummer",
        "Aftaleposition",
        "Aftalestatus",
        "Aftaletype",
        "Årsag_til_luk_aftale",
        "Besvaret",
        "Bilagsnummer",
        "Forretningspartner",
        "Kommune_kode",
        "Konvertering",
        "Lukket_den",
        "Niveau_Aftale_Position",
        "Oprettet_den",
        "Position",
        "System_dato",
        "Tilføjelsesdato",
        "UdlBeløb_int._valuta",
        "Valuta",
    ],

    "Forretningspartner": [
        "BW_Opdateringsmode",
        "Datafordeleren_UUID",
        "Forretningspartner",
        "Forretningspartner-GUID",
        "Gyldig_fra",
        "Gyldig_til",
        "Identifikationsart",
        # "Identifikationsnr.",  # Removed, as these often contain CPR
        "Klient",
        "Slettet",
    ],

    "Indbetalinger": [
        "Afdeling",
        "Afklaringsstatus",
        "Aftale",
        "Aftalekonto",
        "Annuller_status",
        "Art_kilde",
        "Bankafregningskonto",
        "Bankforbindelse",
        "Beløb",
        "Betalings_art",
        "Betalingsidentifikator",
        "Betalingsmåde",
        "Betalingsretning",
        "Bilagsart",
        "Firmakode",
        "Forretningsområde",
        "Forretningspartner",
        "Kasse",
        "Kommune_kode",
        "Konto-ID",
        "Langtekst",
        "Løbenummer",
        "Oprettet_den",
        "Skæringsdato",
        "Tidsstempel_for_deltaekstrakt.",
        "Underapplikation",
        "Valørdato",
        "Valuta",
        "Varighed_af_afklaring",
    ],

    "Opsaetning-Aftalekontotype": [
        "Aftalekontotype",
        "Klient",
        "Kontotype_tekst",
        "Sprognøgle",
    ],

    "Opsaetning-Rykkerniveau": [
        "Betegnelse",
        "Kommune_kode",
        "Rykkeniveau",
        "Rykkeprocedure",
        "Sprognøgle",
    ],

    "RIM-aftale-rater": [
        "Ændret_den",
        "Aftale",
        "Aftale_saldo",
        "Aftalekonto",
        "Aftalekontotype",
        "Aftalenummer",
        "Aftalestatus",
        "Aftaletype",
        "Basisdato_renteberegning",
        "Bilagsnummer",
        "Creation_Amount",
        "Deltransaktion",
        "EFI-nummer",
        "Forældelsesdato",
        "Fordringstype",
        "Forretningspartner",
        "Gentagelsesposition",
        "Henstand_til",
        "Hovedtransaktion",
        "Indholdsart",
        "Kommune_kode",
        "Konvertering_status",
        "KravsType",
        "Markering_for_tilbagekald",
        "Nettoforfald",
        "Oprettet_den",
        "Original_Amount",
        "Position",
        "Produktionsenh.",
        "Ratespecifikation",
        "ReturAarsagKode",
        "ReturÅrsagText",
        "Returdato",
        "SBS_Document_Number",
        "SBS_dokumentnummer",
        "Sidste_rentefrie_indbetalingsdato",
        "Slettes",
        "Slutdato_for_forrentn.",
        "SRI_dato",
        "Status",
        "Stiftelsesdato",
        "System",
        "System_dato",
        "Text_Position_Number",
        "Tilb._Virkningsdato",
        "TilbageAarsagKode",
        "UdlBeløb_int._valuta",
        "Udligningsdato",
        "Valørdato",
        "Valuta",
        "Ydelsesperiode_fra",
        "Ydelsesperiode_til",
    ],

    "RIM-aftale-renter": [
        "Ændret_den",
        "Afklarings_status",
        "Aftalenummer",
        "Aftalestatus",
        "Aftaletype",
        "Basisdato_renteberegning",
        "EFI-nummer",
        "Egen_reference",
        "Forældelsesdato",
        "Fordring_artskode",
        "Fordring_kategorikode",
        "Forretningspartner",
        "Historisk_modtagelsesdato",
        "Hovedfordring_id",
        "Intr-posnr",
        "Kommune_kode",
        "Konvertering_status",
        "KravsType",
        "Markering_for_tilbagekald",
        "Min._beløb_ignoreret",
        "Modtagelsesdato",
        "Oprettet_den",
        "Oprettet_kl.",
        "Overtagelse_af_inddrivelsesrenter",
        "Periodetype_beskrivelse",
        "P-nummer",
        "Produktionsenh.",
        "Rente,_år_til_dato_beløb",
        "Rente,_år_til_dato_beløb,_DKK",
        "Rentebeløb",
        "Rentebeløb,_DKK",
        "Renteperiode_slut-dato",
        "Renteperiode_start-dato",
        "ReturAarsagKode",
        "ReturÅrsagText",
        "Returdato",
        "Slutdato_for_forrentn.",
        "System_dato",
        "Tilb._Virkningsdato",
        "TilbageAarsagKode",
        "Tjek_af_nr._I_Basissystem",
        "Typekode",
        "Udledt_fra_betaling",
        "Udligningsdato",
        "Underretnings-id",
        "Valuta",
        "Valutakode",
    ],

    "RIM-aftale": [
        "Åbent_beløb_for_perioden",
        "ActionStatusCode",
        "Ændret_den",
        "Ændringsårsagskode",
        "Ændringsårsagstekst",
        "Aftalenummer",
        "Aftalestatus",
        "Aftaletype",
        "Afvis",
        "Aktionkode",
        "Aktions-id",
        "Basisdato_renteberegning",
        "Beløb",
        "Beløb_accepteret",
        "Bilagsnummer",
        "EFI-nummer",
        "Forældelsesdato",
        "Forretningspartner",
        "Kommune_kode",
        "KravsType",
        "Krydsende_handling",
        "Markering_for_tilbagekald",
        "Medhæfter_status",
        "Modtagelsesdato",
        "Oprettet_den",
        "Oprettet_kl.",
        "Recall_Amount",
        "Reduceret_beløb",
        "Reference_til_ændring",
        "Rest_beløb_markering",
        "RestBeløb",
        "ReturAarsagKode",
        "ReturÅrsagText",
        "Returdato",
        "RIM_ændringsdato",
        "SBS_dokumentnummer",
        "Slutdato_for_forrentn.",
        "Snitflade_Status",
        "Status",
        "System_dato",
        "Tilb._Virkningsdato",
        "TilbageAarsagKode",
        "Trans_Beløb",
        "Trans_flag",
        "Trans_header_ID",
        "Trans_sekvens_nr.",
        "Transaktion_identifikator",
        "Transdato",
        "Transtid",
        "UdlBeløb_int._valuta",
        "Udligningsdato",
        "UUID",
        "Valuta",
        "Valutanøgle",
        "Virkningsdato",
    ],

    "Rykker": [
        "Aftale",
        "Aftalekonto",
        "Aftalekonto_ikke_entydig",
        "Bilagsnummer",
        "Dato-ID",
        "Delposition",
        "Firmakode",
        "Forretningspartner",
        "Gentagelsesposition",
        "Identifikation",
        "Kommune_kode",
        "Nettoforfald",
        "Nyt_rykkeniveau",
        "Position",
        "Printdato",
        "Rentebilag",
        "Rykkebeløb",
        "Rykkeniveau",
        "Rykkeniveautype",
        "Rykkeprocedure",
        "Rykker_annulleret",
        "Rykkerenter",
        "Rykkertæller",
        "Rykkespærreårsag",
        "Segment",
        "Skæringsdato",
        "Statistiknøgle",
        "Suspenderings-rykkeniv.",
        "Udskrevet",
        "Udstedelsesdato",
        "Valuta",
    ],

    "UU-aftale-haefter": [
        "Aftale",
        "Aftalekonto",
        "Aftalenummer",
        "BetFormReference",
        "Forretningspartner",
        "Hæfter_fjernet",
        "Hæfter_tilføjet",
        "Hovedhæfter",
        "Klient",
        "Kommune_kode",
    ],

    "UU-aftale": [
        "Aftale",
        "Aftalekonto",
        "Aftalenummer",
        "Aftalestatus",
        "Aftaletype",
        "Beløb",
        "Bilagsnummer",
        "Deltransaktion",
        "Hovedtransaktion",
        "Indholdsart",
        "Kommune_kode",
        "Position",
        "Udligningsstatus",
        "Valuta",
    ],
}

"""
Data type mappings for KMD Opus ODE CSV files
Based on integration specification version 1.2

Type mapping rules:
- CHAR -> 'text'
- DATS -> 'date'
- NUMC -> 'int'
- CURR -> 'number'
- DEC -> 'number'
- INT4 -> 'int'
- CUKY -> 'text'
- CLNT -> 'text'
- TIMS -> 'text'
- LANG -> 'text'
- RAW -> 'text'
- INT1 -> 'int'
"""

data_types = {  # This table maps columns to datatypes, as defind in the KMD API docs.
    'Bilag-master': {
        "Gentagelsesposition": 'int',
        'AfregnPeriode_fra': 'date',
        'AfregnPeriode_til': 'date',
        'Afskrivningsårsag': 'text',
        'Aftale': 'text',
        'Aftalekonto': 'text',
        'Aftalekontotype': 'text',
        'Aftalenummer': 'text',
        'Aftalestatus': 'text',
        'Aftaletype': 'text',
        'Applikationsområde': 'text',
        'Artskonto': 'text',
        'Beløb_intern_valuta': 'number',
        'Beløb': 'number',
        'Betalingsordre': 'text',
        'Bilagsart': 'text',
        'Bilagsdato': 'date',
        'Bilagsnummer': 'text',
        'Bilagstype_markering': 'text',
        'BogfDato_udligning': 'date',
        'Bogføringsdato': 'date',
        'Bortposteringsårsag': 'text',
        'Delposition': 'int',
        'Deltransaktion': 'text',
        'Firmakode': 'text',
        'Forretningspartner': 'text',
        'Henstand_til': 'date',
        'Hovedtransaktion': 'text',
        'Indholdsart': 'text',
        'Kommune_kode': 'text',
        'KontofastsætKendet.': 'text',
        'Momsindikator': 'text',
        'Nettoforfald': 'date',
        'Oprindelse': 'text',
        'Position': 'int',
        'Referencebilagsnr.': 'text',
        'Referencenøgle': 'text',
        'Referenceoperation': 'text',
        'Registreringsdato': 'date',
        'Rentenøgle': 'text',
        'Rykkeprocedure': 'text',
        'SBS_dokumentnummer': 'text',
        'Skæringsdato': 'date',
        'Statistiknøgle': 'text',
        'Tilbageført_via': 'text',
        'Udligningsårsag': 'text',
        'Udligningsbeløb': 'number',
        'Udligngningstype': 'text',
        'Udligningsbilag': 'text',
        'Udligningsdato': 'date',
        'Udligningsstatus': 'text',
        'Udligningsvaluta': 'text',
        'Valørdato_udligning': 'date',
        'Valuta': 'text',
    },

    'Bilag-aaben': {
        'Aftaleindhold': 'text',
        'Aftalekonto': 'text',
        'Aftalekontotype': 'text',
        'Aftalenummer': 'text',
        'Aftalestatus': 'text',
        'Aftaletype': 'text',
        'Antal_poster': 'int',
        'Beløb_intern_valuta': 'number',
        'Beløb': 'number',
        'BevillAnsvarssted': 'text',
        'Bevillingsposition': 'text',
        'Bevillingsprogram': 'text',
        'Bilagsdato': 'date',
        'Bilagsnummer': 'text',
        'Bogføringsdato': 'date',
        'Dato-ID': 'date',
        'Deltransaktion': 'text',
        'Firmakode': 'text',
        'Forretningspartner': 'text',
        'Funktionsområde': 'text',
        'Henstand_til': 'date',
        'Hovedtransaktion': 'text',
        'Identifikation': 'text',
        'Indholdsart': 'text',
        'Kapitalmidler': 'text',
        'Klient': 'text',
        'Kommune_kode': 'text',
        'Kredit_oprindelses_dato': 'date',
        'Landenøgle': 'text',
        'Nettoforfald': 'date',
        'Original-FI-område': 'text',
        'Periodenøgle': 'text',
        'Position': 'int',
        'Positionstekst': 'text',
        'Postnummer': 'text',
        'Referencebilagsnr.': 'text',
        'Registreringsdato': 'date',
        'Rykkeniveau': 'int',
        'Rykkeniveautype': 'text',
        'Rykkeprocedure': 'text',
        'Rykkeproceduretype': 'text',
        'SBS_dokumentnummer': 'text',
        'Skæringsdato': 'date',
        'Sorteringsbetegnelse': 'text',
        'Statistiknøgle': 'text',
        'Udligning_kredit_oprindelse': 'text',
        'Udligningsstatus': 'text',
        'Valuta': 'text',
    },

    'Bilag-lukket': {
        "Intervalnummer": 'int',
        "Recordnummer": 'int',
        'Afskrivningsårsag': 'text',
        'Afskrivningsdato': 'date',
        'Aftaleindhold': 'text',
        'Aftalekonto': 'text',
        'Aftalekontotype': 'text',
        'Aftalenummer': 'text',
        'Aftalestatus': 'text',
        'Aftaletype': 'text',
        'Antal_poster': 'int',
        'Bankafregningskonto': 'text',
        'Beløb_intern_valuta': 'number',
        'Beløb': 'number',
        'BevillAnsvarssted': 'text',
        'Bevillingsposition': 'text',
        'Bevillingsprogram': 'text',
        'Bilagsdato': 'date',
        'Bilagsnummer': 'text',
        'Bilagstype_markering': 'text',
        'BogfDato_udligning': 'date',
        'Bogføringsdato': 'date',
        'Bortposteringsårsag': 'text',
        'Dato-ID': 'date',
        'Deltransaktion': 'text',
        'Firmakode': 'text',
        'Forretningspartner': 'text',
        'Fra': 'date',
        'Funktionsområde': 'text',
        'Henstand_til': 'date',
        'Hovedtransaktion': 'text',
        'Identifikation': 'text',
        'Indbetalingstype': 'text',
        'Indholdsart': 'text',
        'Kapitalmidler': 'text',
        'Klient': 'text',
        'Kommune_kode': 'text',
        'Kredit_oprindelses_dato': 'date',
        'Landenøgle': 'text',
        'Nettoforfald': 'date',
        'Original-FI-område': 'text',
        'Position': 'int',
        'Postnummer': 'text',
        'Referencebilagsnr.': 'text',
        'Registreringsdato': 'date',
        'Rykkeniveau': 'int',
        'Rykkeprocedure': 'text',
        'SBS_dokumentnummer': 'text',
        'Sorteringsbetegnelse': 'text',
        'Statistiknøgle': 'text',
        'Til': 'date',
        'Tilbageført_via': 'text',
        'Udligning_kredit_oprindelse': 'text',
        'Udligning': 'date',
        'Udligningsårsag': 'text',
        'Udligningsbeløb': 'number',
        'Udligningsbilag': 'text',
        'Udligningsdato': 'date',
        'Udligningsstatus': 'text',
        'Udligningsvaluta': 'text',
        'Underapplikation': 'text',
        'Valørdato_udligning': 'date',
        'Valuta': 'text',
    },

    'Indbetalinger': {
        'Afdeling': 'text',
        'Afklaringsstatus': 'text',
        'Aftale': 'text',
        'Aftalekonto': 'text',
        'Annuller_status': 'text',
        'Art_kilde': 'text',
        'Bankafregningskonto': 'text',
        'Bankforbindelse': 'text',
        'Beløb': 'number',
        'Betalings_art': 'text',
        'Betalingsidentifikator': 'text',
        'Betalingsmåde': 'text',
        'Betalingsretning': 'text',
        'Bilagsart': 'text',
        'Firmakode': 'text',
        'Forretningsområde': 'text',
        'Forretningspartner': 'text',
        'Kasse': 'text',
        'Kommune_kode': 'text',
        'Konto-ID': 'text',
        'Langtekst': 'text',
        'Løbenummer': 'int',
        'Oprettet_den': 'date',
        'Skæringsdato': 'date',
        'Tidsstempel_for_deltaekstrakt.': 'date',
        'Underapplikation': 'text',
        'Valørdato': 'date',
        'Valuta': 'text',
        'Varighed_af_afklaring': 'int',
    },

    'Rykker': {
        'Aftale': 'text',
        'Aftalekonto_ikke_entydig': 'text',
        'Aftalekonto': 'text',
        'Bilagsnummer': 'text',
        'Dato-ID': 'date',
        'Delposition': 'int',
        'Firmakode': 'text',
        'Forretningspartner': 'text',
        'Gentagelsesposition': 'int',
        'Identifikation': 'text',
        'Kommune_kode': 'text',
        'Nettoforfald': 'date',
        'Nyt_rykkeniveau': 'int',
        'Position': 'int',
        'Printdato': 'date',
        'Rentebilag': 'text',
        'Rykkebeløb': 'number',
        'Rykkeniveau': 'number',
        'Rykkeniveautype': 'text',
        'Rykkeprocedure': 'text',
        'Rykker_annulleret': 'text',
        'Rykkerenter': 'number',
        'Rykkertæller': 'int',
        'Rykkespærreårsag': 'text',
        'Segment': 'text',
        'Skæringsdato': 'date',
        'Statistiknøgle': 'text',
        'Suspenderings-rykkeniv.': 'text',
        'Udskrevet': 'text',
        'Udstedelsesdato': 'date',
        'Valuta': 'text',
    },

    'FP-aftale': {
        'AA_type': 'text',
        'Ændret_den': 'date',
        'Aftale': 'text',
        'Aftalekonto': 'text',
        'Aftalenummer': 'text',
        'Aftaleposition': 'int',
        'Aftalestatus': 'text',
        'Aftaletype': 'text',
        'Årsag_til_luk_aftale': 'text',
        'Besvaret': 'date',
        'Bilagsnummer': 'text',
        'Forretningspartner': 'text',
        'Kommune_kode': 'text',
        'Konvertering': 'text',
        'Lukket_den': 'date',
        'Niveau_Aftale_Position': 'text',
        'Oprettet_den': 'date',
        'Position': 'int',
        'System_dato': 'date',
        'Tilføjelsesdato': 'date',
        'UdlBeløb_int._valuta': 'number',
        'Valuta': 'text',
    },

    'UU-aftale': {
        'Aftalestatus': 'text',
        'Aftaletype': 'text',
        'Aftalenummer': 'text',
        'Indholdsart': 'text',
        'Aftale': 'text',
        'Aftalekonto': 'text',
        'Deltransaktion': 'text',
        'Bilagsnummer': 'text',
        'Position': 'int',
        'Hovedtransaktion': 'text',
        'Udligningsstatus': 'text',
        'Beløb': 'number',
        'Valuta': 'text',
        'Kommune_kode': 'text'
    },

    'UU-aftale-haefter': {
        'Klient': 'text',
        'Aftale': 'text',
        'Aftalekonto': 'text',
        'Aftalenummer': 'text',
        'BetFormReference': 'text',
        'Forretningspartner': 'text',
        'Hovedhæfter': 'text',
        'Hæfter_fjernet': 'date',
        'Hæfter_tilføjet': 'date',
        'Kommune_kode': 'text'
    },

    'RIM-aftale': {
        'Åbent_beløb_for_perioden': 'number',
        'Ændret_den': 'date',
        'Ændringsårsagstekst': 'text',
        'Ændringsårsagskode': 'text',
        'Aftalenummer': 'text',
        'Aftalestatus': 'text',
        'Aftaletype': 'text',
        'Afvis': 'text',
        'ActionStatusCode': 'text',
        'Aktionkode': 'text',
        'Aktions-id': 'int',
        'Basisdato_renteberegning': 'date',
        'Beløb_accepteret': 'number',
        'Beløb': 'number',
        'Bilagsnummer': 'text',
        'EFI-nummer': 'int',
        'Forældelsesdato': 'date',
        'Forretningspartner': 'text',
        'Kommune_kode': 'text',
        'KravsType': 'text',
        'Krydsende_handling': 'text',
        'Markering_for_tilbagekald': 'text',
        'Medhæfter_status': 'text',
        'Modtagelsesdato': 'date',
        'Oprettet_den': 'date',
        'Oprettet_kl.': 'text',
        'Recall_Amount': 'number',
        'Reduceret_beløb': 'text',
        'Reference_til_ændring': 'text',
        'Rest_beløb_markering': 'text',
        'RestBeløb': 'number',
        'ReturAarsagKode': 'text',
        'ReturÅrsagText': 'text',
        'Returdato': 'date',
        'RIM_ændringsdato': 'number',
        'SBS_dokumentnummer': 'text',
        'Slutdato_for_forrentn.': 'date',
        'Snitflade_Status': 'text',
        'Status': 'text',
        'System_dato': 'date',
        'Tilb._Virkningsdato': 'date',
        'TilbageAarsagKode': 'text',
        'Trans_Beløb': 'number',
        'Trans_flag': 'text',
        'Trans_header_ID': 'int',
        'Trans_sekvens_nr.': 'int',
        'Transaktion_identifikator': 'text',
        'Transdato': 'date',
        'Transtid': 'text',
        'UdlBeløb_int._valuta': 'number',
        'Udligningsdato': 'date',
        'UUID': 'text',
        'Valuta': 'text',
        'Valutanøgle': 'text',
        'Virkningsdato': 'date',
    },

    'RIM-aftale-rater': {
        'Ændret_den': 'date',
        'Aftale': 'text',
        'Aftalekonto': 'text',
        'Aftalekontotype': 'text',
        'Aftalenummer': 'text',
        'Aftale_saldo': 'number',
        'Aftalestatus': 'text',
        'Aftaletype': 'text',
        'Basisdato_renteberegning': 'date',
        'Bilagsnummer': 'text',
        'Creation_Amount': 'number',
        'Deltransaktion': 'text',
        'EFI-nummer': 'int',
        'Forældelsesdato': 'date',
        'Fordringstype': 'text',
        'Forretningspartner': 'text',
        'Gentagelsesposition': 'int',
        'Henstand_til': 'date',
        'Hovedtransaktion': 'text',
        'Indholdsart': 'text',
        'Kommune_kode': 'text',
        'Konvertering_status': 'text',
        'KravsType': 'text',
        'Markering_for_tilbagekald': 'text',
        'Nettoforfald': 'date',
        'Oprettet_den': 'date',
        'Original_Amount': 'number',
        'Position': 'int',
        'Produktionsenh.': 'int',
        'Ratespecifikation': 'text',
        'ReturÅrsagText': 'text',
        'ReturAarsagKode': 'text',
        'Returdato': 'date',
        'SBS_dokumentnummer': 'text',
        'SBS_Document_Number': 'text',
        'Sidste_rentefrie_indbetalingsdato': 'text',
        'Slettes': 'text',
        'Slutdato_for_forrentn.': 'date',
        'SRI_dato': 'date',
        'Status': 'text',
        'Stiftelsesdato': 'date',
        'System_dato': 'date',
        'System': 'text',
        'Text_Position_Number': 'number',
        'Tilb._Virkningsdato': 'date',
        'TilbageAarsagKode': 'text',
        'UdlBeløb_int._valuta': 'number',
        'Udligningsdato': 'date',
        'Valørdato': 'date',
        'Valuta': 'text',
        'Ydelsesperiode_fra': 'date',
        'Ydelsesperiode_til': 'date',
    },

    'RIM-aftale-renter': {
        'Ændret_den': 'date',
        'Afklarings_status': 'text',
        'Aftalenummer': 'text',
        'Aftalestatus': 'text',
        'Aftaletype': 'text',
        'Basisdato_renteberegning': 'date',
        'EFI-nummer': 'int',
        'Egen_reference': 'text',
        'Forældelsesdato': 'date',
        'Fordring_artskode': 'text',
        'Fordring_kategorikode': 'text',
        'Forretningspartner': 'text',
        'Historisk_modtagelsesdato': 'date',
        'Hovedfordring_id': 'int',
        'Intr-posnr': 'int',
        'Kommune_kode': 'text',
        'Konvertering_status': 'text',
        'KravsType': 'text',
        'Markering_for_tilbagekald': 'text',
        'Min._beløb_ignoreret': 'text',
        'Modtagelsesdato': 'date',
        'Oprettet_den': 'date',
        'Oprettet_kl.': 'text',
        'Overtagelse_af_inddrivelsesrenter': 'text',
        'P-nummer': 'int',
        'Periodetype_beskrivelse': 'text',
        'Produktionsenh.': 'int',
        'Rente,_år_til_dato_beløb,_DKK': 'number',
        'Rente,_år_til_dato_beløb': 'number',
        'Rentebeløb,_DKK': 'number',
        'Rentebeløb': 'number',
        'Renteperiode_slut-dato': 'date',
        'Renteperiode_start-dato': 'date',
        'ReturAarsagKode': 'text',
        'ReturÅrsagText': 'text',
        'Returdato': 'date',
        'Slutdato_for_forrentn.': 'date',
        'System_dato': 'date',
        'Tilb._Virkningsdato': 'date',
        'TilbageAarsagKode': 'text',
        'Tjek_af_nr._I_Basissystem': 'text',
        'Typekode': 'text',
        'Udledt_fra_betaling': 'text',
        'Udligningsdato': 'date',
        'Underretnings-id': 'int',
        'Valuta': 'text',
        'Valutakode': 'text',
    },

    'Forretningspartner': {
        'Klient': 'text',
        'Forretningspartner': 'text',
        'Identifikationsart': 'text',
        'Identifikationsnr.': 'text',
        'Gyldig_fra': 'date',
        'Gyldig_til': 'date',
        'Datafordeleren_UUID': 'text',
        'Forretningspartner-GUID': 'text',
        'BW_Opdateringsmode': 'text',
        'Slettet': 'text'
    },

    'Aftaleindhold': {
        'Aftaleindhold': 'text',
        'Oprettet_af': 'text',
        'Oprettet_den': 'date',
        'Ændret_af': 'text',
        'Ændret_den': 'date',
        'Indholdsart': 'text',
        'Bet._aftaleindhold': 'text',
        'Nummer_i_basissystem': 'text',
        'Kommune_kode': 'text'
    },

    'BO-aftale': {
        'Aftalestatus': 'text',
        'Aftaletype': 'text',
        'Aftalenummer': 'text',
        'Bilagsnummer': 'text',
        'Position': 'int',
        'Oprettet_beløb': 'number',
        'Valuta': 'text',
        'Første_anmeldelse': 'number',
        'Indbetalt_af_bobestyrer': 'number',
        'Fjernet': 'text',
        'Bobehandling': 'text',
        'Indholdsart': 'text',
        'Deltransaktion': 'text',
        'Hovedtransaktion': 'text',
        'Aftalekonto': 'text',
        'Aftale': 'text',
        'Kommune_kode': 'text',
        'Restbeløb': 'number',
        'Afskrevet': 'number',
        'Ændringer_efter_første_anmeld': 'number'
    },

    'BO-aftale-haendelse': {
        'Klient': 'text',
        'Aftalenummer': 'text',
        'Bobehandling': 'text',
        'Ekstern_reference_nøgle': 'text',
        'Udtrækstype': 'text',
        'Korrespondanceart': 'text',
        'Printdato': 'date',
        'Afskrevet': 'number',
        'Afskrivnings_dato': 'date',
        'Betalingsdato': 'date',
        'Valuta': 'text',
        'Kommune_kode': 'text',
        'Beløb': 'number',
        'Indbetalt_af_bobestyrer': 'text',
    },

    'Opsaetning-Aftalekontotype': {
        'Klient': 'number',
        'Sprognøgle': 'text',
        'Aftalekontotype': 'text',
        'Kontotype_tekst': 'text'
    },

    'Opsaetning-Rykkerniveau': {
        'Sprognøgle': 'text',
        'Rykkeprocedure': 'text',
        'Rykkeniveau': 'int',
        'Betegnelse': 'text',
        'Kommune_kode': 'text'
    }
}
