# pylint: disable=too-many-lines
"""This contains a list of table columns to use for each table in the data set."""

from sqlalchemy import String, Date, Numeric, Integer

table_keys = {  # This table contains the keys used in the database to identify each entry.
    "Aftaleindhold":                ["Aftaleindhold"],
    "BO-aftale-haendelse":          ["Ekstern_reference_nøgle"],
    "BO-aftale":                    ["Aftalenummer", "Bilagsnummer", "Position"],
    "Bilag-lukket":                 ["Dato-ID", "Identifikation", "Intervalnummer", "Recordnummer"],
    "Bilag-master":                 ["Bilagsnummer", "Gentagelsesposition", "Position", "Delposition"],
    "Forretningspartner":           ["Klient", "Forretningspartner", "Identifikationsart", "Forretningspartner-GUID"],  # These were removed as they often contain CPRs: "Identifikationsnr",
    "Indbetalinger":                ["Art_kilde", "Betalingsidentifikator", "Løbenummer"],
    "Opsaetning-Aftalekontotype":   ["Klient", "Sprognøgle", "Aftalekontotype"],
    "Opsaetning-Rykkerniveau":      ["Sprognøgle", "Rykkeprocedure", "Rykkeniveau"],
    "RIM-aftale-renter":            ["Aftalenummer", "Intr-posnr"],
    "Rykker":                       ["Dato-ID", "Identifikation", "Forretningspartner", "Aftalekonto", "Rykkertæller", "Bilagsnummer", "Gentagelsesposition", "Position", "Delposition"],
    "UU-aftale-haefter":            ["Klient", "Aftalenummer", "Forretningspartner"],
    "FP-aftale":                    None,
    "RIM-aftale-rater":             None,
    "RIM-aftale":                   None,
    "Bilag-aaben":                  None,
    "UU-aftale":                    None,
}

table_date_columns = {  # This table contains the date columns, that are used to define when they were added, for filtering on a date range.
    "BO-aftale-haendelse":          ["Afskrivnings_dato", "Betalingsdato"],
    "FP-aftale":                    "Oprettet_den",
    "Indbetalinger":                "Oprettet_den",
    "RIM-aftale-rater":             "Oprettet_den",
    "RIM-aftale-renter":            "Oprettet_den",
    "RIM-aftale":                   "Oprettet_den",
    "Rykker":                       "Udstedelsesdato",
    "Bilag-aaben":                  "Bogføringsdato",
    "Bilag-lukket":                 "Bogføringsdato",
    "Bilag-master":                 "Registreringsdato",
    "BO-aftale":                    None,
    "Forretningspartner":           None,
    "Opsaetning-Aftalekontotype":   None,
    "Opsaetning-Rykkerniveau":      None,
    "UU-aftale-haefter":            None,
    "UU-aftale":                    None,
}

table_used_columns = {  # This table defines all the columns we actually use from each table.
    "Aftaleindhold": [
        "Aftaleindhold",
        "Oprettet_af",
        "Oprettet_den",
        "Ændret_af",
        "Ændret_den",
        "Indholdsart",
        "Bet_aftaleindhold",
        "Nummer_i_basissystem",
        "Kommune_kode"
    ],

    "BO-aftale-haendelse": [
        "Afskrevet",
        "Afskrivnings_dato",
        "Aftalenummer",
        "Beløb",
        "Betalingsdato",
        "Bobehandling",
        "Ekstern_reference_nøgle",
        "Indbetalt_af_bobestyrer",
        "Klient",
        "Kommune_kode",
        "Korrespondanceart",
        "Printdato",
        "Udtrækstype",
        "Valuta",
    ],

    "BO-aftale": [
        "Ændringer_efter_første_anmeld",
        "Afskrevet",
        "Aftale",
        "Aftalekonto",
        "Aftalenummer",
        "Aftalestatus",
        "Aftaletype",
        "Bilagsnummer",
        "Bobehandling",
        "Deltransaktion",
        "Fjernet",
        "Første_anmeldelse",
        "Hovedtransaktion",
        "Indbetalt_af_bobestyrer",
        "Indholdsart",
        "Kommune_kode",
        "Oprettet_beløb",
        "Position",
        "Restbeløb",
        "Valuta",
    ],

    "Bilag-aaben": [
        "Aftaleindhold",
        "Aftalekonto",
        "Aftalekontotype",
        "Aftalenummer",
        "Aftalestatus",
        "Aftaletype",
        "Antal_poster",
        "Beløb",
        "Beløb_intern_valuta",
        "BevillAnsvarssted",
        "Bevillingsposition",
        "Bevillingsprogram",
        "Bilagsdato",
        "Bilagsnummer",
        "Bogføringsdato",
        "Dato-ID",
        "Deltransaktion",
        "Firmakode",
        "Forretningspartner",
        "Funktionsområde",
        "Henstand_til",
        "Hovedtransaktion",
        "Identifikation",
        "Indholdsart",
        "Kapitalmidler",
        "Klient",
        "Kommune_kode",
        "Kredit_oprindelses_dato",
        "Landenøgle",
        "Nettoforfald",
        "Original-FI-område",
        "Periodenøgle",
        "Position",
        "Positionstekst",
        "Postnummer",
        "Referencebilagsnr",
        "Registreringsdato",
        "Rykkeniveau",
        "Rykkeniveautype",
        "Rykkeprocedure",
        "Rykkeproceduretype",
        "SBS_dokumentnummer",
        "Skæringsdato",
        "Sorteringsbetegnelse",
        "Statistiknøgle",
        "Udligning_kredit_oprindelse",
        "Udligningsstatus",
        "Valuta"
    ],

    "Bilag-lukket": [
        "Afskrivningsårsag",
        "Afskrivningsdato",
        "Aftaleindhold",
        "Aftalekonto",
        "Aftalekontotype",
        "Aftalenummer",
        "Aftalestatus",
        "Aftaletype",
        "Antal_poster",
        "Bankafregningskonto",
        "Beløb",
        "Beløb_intern_valuta",
        "BevillAnsvarssted",
        "Bevillingsposition",
        "Bevillingsprogram",
        "Bilagsdato",
        "Bilagsnummer",
        "Bilagstype_markering",
        "BogfDato_udligning",
        "Bogføringsdato",
        "Bortposteringsårsag",
        "Dato-ID",
        "Deltransaktion",
        "Firmakode",
        "Forretningspartner",
        "Fra",
        "Funktionsområde",
        "Henstand_til",
        "Hovedtransaktion",
        "Identifikation",
        "Indbetalingstype",
        "Indholdsart",
        "Intervalnummer",
        "Kapitalmidler",
        "Klient",
        "Kommune_kode",
        "Kredit_oprindelses_dato",
        "Landenøgle",
        "Nettoforfald",
        "Original-FI-område",
        "Position",
        "Postnummer",
        "Recordnummer",
        "Referencebilagsnr",
        "Registreringsdato",
        "Rykkeniveau",
        "Rykkeprocedure",
        "SBS_dokumentnummer",
        "Sorteringsbetegnelse",
        "Statistiknøgle",
        "Til",
        "Tilbageført_via",
        "Udligning",
        "Udligning_kredit_oprindelse",
        "Udligningsårsag",
        "Udligningsbeløb",
        "Udligningsbilag",
        "Udligningsdato",
        "Udligningsstatus",
        "Udligningsvaluta",
        "Underapplikation",
        "Valørdato_udligning",
        "Valuta"
    ],

    "Bilag-master": [
        "AfregnPeriode_fra",
        "AfregnPeriode_til",
        "Afskrivningsårsag",
        "Aftale",
        "Aftalekonto",
        "Aftalekontotype",
        "Aftalenummer",
        "Aftalestatus",
        "Aftaletype",
        "Applikationsområde",
        "Artskonto",
        "Beløb",
        "Beløb_intern_valuta",
        "Betalingsordre",
        "Bilagsart",
        "Bilagsdato",
        "Bilagsnummer",
        "Bilagstype_markering",
        "BogfDato_udligning",
        "Bogføringsdato",
        "Bortposteringsårsag",
        "Delposition",
        "Deltransaktion",
        "Firmakode",
        "Forretningspartner",
        "Gentagelsesposition",
        "Henstand_til",
        "Hovedtransaktion",
        "Indholdsart",
        "Kommune_kode",
        "KontofastsætKendet",
        "Momsindikator",
        "Nettoforfald",
        "Oprindelse",
        "Position",
        "Referencebilagsnr",
        "Referencenøgle",
        "Referenceoperation",
        "Registreringsdato",
        "Rentenøgle",
        "Rykkeprocedure",
        "SBS_dokumentnummer",
        "Skæringsdato",
        "Statistiknøgle",
        "Tilbageført_via",
        "Udligngningstype",
        "Udligningsårsag",
        "Udligningsbeløb",
        "Udligningsbilag",
        "Udligningsdato",
        "Udligningsstatus",
        "Udligningsvaluta",
        "Valørdato_udligning",
        "Valuta",
    ],

    "FP-aftale": [
        "AA_type",
        "Ændret_den",
        "Aftale",
        "Aftalekonto",
        "Aftalenummer",
        "Aftaleposition",
        "Aftalestatus",
        "Aftaletype",
        "Årsag_til_luk_aftale",
        "Besvaret",
        "Bilagsnummer",
        "Forretningspartner",
        "Kommune_kode",
        "Konvertering",
        "Lukket_den",
        "Niveau_Aftale_Position",
        "Oprettet_den",
        "Position",
        "System_dato",
        "Tilføjelsesdato",
        "UdlBeløb_int_valuta",
        "Valuta",
    ],

    "Forretningspartner": [
        "BW_Opdateringsmode",
        "Datafordeleren_UUID",
        "Forretningspartner",
        "Forretningspartner-GUID",
        "Gyldig_fra",
        "Gyldig_til",
        "Identifikationsart",
        # "Identifikationsnr",  # Removed, as these often contain CPR
        "Klient",
        "Slettet",
    ],

    "Indbetalinger": [
        "Afdeling",
        "Afklaringsstatus",
        "Aftale",
        "Aftalekonto",
        "Annuller_status",
        "Art_kilde",
        "Bankafregningskonto",
        "Bankforbindelse",
        "Beløb",
        "Betalings_art",
        "Betalingsidentifikator",
        "Betalingsmåde",
        "Betalingsretning",
        "Bilagsart",
        "Firmakode",
        "Forretningsområde",
        "Forretningspartner",
        "Kasse",
        "Kommune_kode",
        "Konto-ID",
        "Langtekst",
        "Løbenummer",
        "Oprettet_den",
        "Skæringsdato",
        "Tidsstempel_for_deltaekstrakt",
        "Underapplikation",
        "Valørdato",
        "Valuta",
        "Varighed_af_afklaring",
    ],

    "Opsaetning-Aftalekontotype": [
        "Aftalekontotype",
        "Klient",
        "Kontotype_tekst",
        "Sprognøgle",
    ],

    "Opsaetning-Rykkerniveau": [
        "Betegnelse",
        "Kommune_kode",
        "Rykkeniveau",
        "Rykkeprocedure",
        "Sprognøgle",
    ],

    "RIM-aftale-rater": [
        "Ændret_den",
        "Aftale",
        # "Aftale_saldo",  # Missing from 0751_ODE_2024-10-04_002_10-RIM-aftale-rater_Total_001af53.csv
        "Aftalekonto",
        "Aftalekontotype",
        "Aftalenummer",
        "Aftalestatus",
        "Aftaletype",
        "Basisdato_renteberegning",
        "Bilagsnummer",
        "Creation_Amount",
        "Deltransaktion",
        "EFI-nummer",
        "Forældelsesdato",
        "Fordringstype",
        "Forretningspartner",
        "Gentagelsesposition",
        "Henstand_til",
        "Hovedtransaktion",
        "Indholdsart",
        "Kommune_kode",
        "Konvertering_status",
        "KravsType",
        "Markering_for_tilbagekald",
        "Nettoforfald",
        "Oprettet_den",
        "Original_Amount",
        "Position",
        "Produktionsenh",
        "Ratespecifikation",
        "ReturAarsagKode",
        "ReturÅrsagText",
        "Returdato",
        "SBS_Document_Number",
        "SBS_dokumentnummer",
        "Sidste_rentefrie_indbetalingsdato",
        "Slettes",
        "Slutdato_for_forrentn",
        "SRI_dato",
        "Status",
        "Stiftelsesdato",
        # "System",  # Missing from 0751_ODE_2024-10-04_002_10-RIM-aftale-rater_Total_001af53.csv
        "System_dato",
        "Text_Position_Number",
        "Tilb_Virkningsdato",
        "TilbageAarsagKode",
        "UdlBeløb_int_valuta",
        "Udligningsdato",
        "Valørdato",
        "Valuta",
        "Ydelsesperiode_fra",
        "Ydelsesperiode_til",
    ],

    "RIM-aftale-renter": [
        "Ændret_den",
        "Afklarings_status",
        "Aftalenummer",
        "Aftalestatus",
        "Aftaletype",
        "Basisdato_renteberegning",
        "EFI-nummer",
        "Egen_reference",
        "Forældelsesdato",
        "Fordring_artskode",
        "Fordring_kategorikode",
        "Forretningspartner",
        "Historisk_modtagelsesdato",
        "Hovedfordring_id",
        "Intr-posnr",
        "Kommune_kode",
        "Konvertering_status",
        "KravsType",
        "Markering_for_tilbagekald",
        "Min_beløb_ignoreret",
        "Modtagelsesdato",
        "Oprettet_den",
        "Oprettet_kl",
        "Overtagelse_af_inddrivelsesrenter",
        "Periodetype_beskrivelse",
        "P-nummer",
        "Produktionsenh",
        "Rente,_år_til_dato_beløb",
        "Rente,_år_til_dato_beløb,_DKK",
        "Rentebeløb",
        "Rentebeløb,_DKK",
        "Renteperiode_slut-dato",
        "Renteperiode_start-dato",
        "ReturAarsagKode",
        "ReturÅrsagText",
        "Returdato",
        "Slutdato_for_forrentn",
        "System_dato",
        "Tilb_Virkningsdato",
        "TilbageAarsagKode",
        "Tjek_af_nr_I_Basissystem",
        "Typekode",
        "Udledt_fra_betaling",
        "Udligningsdato",
        "Underretnings-id",
        "Valuta",
        "Valutakode",
    ],

    "RIM-aftale": [
        "Åbent_beløb_for_perioden",
        "ActionStatusCode",
        "Ændret_den",
        "Ændringsårsagskode",
        "Ændringsårsagstekst",
        "Aftalenummer",
        "Aftalestatus",
        "Aftaletype",
        "Afvis",
        "Aktionkode",
        "Aktions-id",
        "Basisdato_renteberegning",
        "Beløb",
        "Beløb_accepteret",
        "Bilagsnummer",
        "EFI-nummer",
        "Forældelsesdato",
        "Forretningspartner",
        "Kommune_kode",
        "KravsType",
        "Krydsende_handling",
        "Markering_for_tilbagekald",
        "Medhæfter_status",
        "Modtagelsesdato",
        "Oprettet_den",
        "Oprettet_kl",
        "Recall_Amount",
        "Reduceret_beløb",
        "Reference_til_ændring",
        "Rest_beløb_markering",
        "RestBeløb",
        "ReturAarsagKode",
        "ReturÅrsagText",
        "Returdato",
        "RIM_ændringsdato",
        "SBS_dokumentnummer",
        "Slutdato_for_forrentn",
        "Snitflade_Status",
        "Status",
        "System_dato",
        "Tilb_Virkningsdato",
        "TilbageAarsagKode",
        "Trans_Beløb",
        "Trans_flag",
        "Trans_header_ID",
        "Trans_sekvens_nr",
        "Transaktion_identifikator",
        "Transdato",
        "Transtid",
        "UdlBeløb_int_valuta",
        "Udligningsdato",
        "UUID",
        "Valuta",
        "Valutanøgle",
        "Virkningsdato",
    ],

    "Rykker": [
        "Aftale",
        "Aftalekonto",
        "Aftalekonto_ikke_entydig",
        "Bilagsnummer",
        "Dato-ID",
        "Delposition",
        "Firmakode",
        "Forretningspartner",
        "Gentagelsesposition",
        "Identifikation",
        "Kommune_kode",
        "Nettoforfald",
        "Nyt_rykkeniveau",
        "Position",
        "Printdato",
        "Rentebilag",
        "Rykkebeløb",
        "Rykkeniveau",
        "Rykkeniveautype",
        "Rykkeprocedure",
        "Rykker_annulleret",
        "Rykkerenter",
        "Rykkertæller",
        "Rykkespærreårsag",
        "Segment",
        "Skæringsdato",
        "Statistiknøgle",
        "Suspenderings-rykkeniv",
        "Udskrevet",
        "Udstedelsesdato",
        "Valuta",
    ],

    "UU-aftale-haefter": [
        "Aftale",
        "Aftalekonto",
        "Aftalenummer",
        "BetFormReference",
        "Forretningspartner",
        "Hæfter_fjernet",
        "Hæfter_tilføjet",
        "Hovedhæfter",
        "Klient",
        "Kommune_kode",
    ],

    "UU-aftale": [
        "Aftale",
        "Aftalekonto",
        "Aftalenummer",
        "Aftalestatus",
        "Aftaletype",
        "Beløb",
        "Bilagsnummer",
        "Deltransaktion",
        "Hovedtransaktion",
        "Indholdsart",
        "Kommune_kode",
        "Position",
        "Udligningsstatus",
        "Valuta",
    ],
}

table_column_alias = {  # This table contains aliases for column names that have changed at some point.
    'Bilag-master': {
        'Bilagstype': 'Bilagsart'
    },
    'Indbetalinger': {
        'Bilagstype': 'Bilagsart'
    },
    'RIM-aftale': {
        'Trans_header-id': 'Trans_header_ID'
    }
}

"""
Data type mappings for KMD Opus ODE CSV files
Based on integration specification version 1.2

Type mapping rules:
- CHAR -> String(255)
- DATS -> Date
- NUMC -> Integer
- CURR -> Numeric(precision=15, scale=2)
- DEC -> Numeric(precision=15, scale=2)
- INT4 -> Integer
- CUKY -> String(255)
- CLNT -> String(255)
- TIMS -> String(255)
- LANG -> String(255)
- RAW -> String(255)
- INT1 -> Integer
"""

data_types = {  # This table maps columns to datatypes, as defind in the KMD API docs.
    'Bilag-master': {
        "Gentagelsesposition": Integer,
        'AfregnPeriode_fra': Date,
        'AfregnPeriode_til': Date,
        'Afskrivningsårsag': String(255),
        'Aftale': String(255),
        'Aftalekonto': String(255),
        'Aftalekontotype': String(255),
        'Aftalenummer': String(255),
        'Aftalestatus': String(255),
        'Aftaletype': String(255),
        'Applikationsområde': String(255),
        'Artskonto': String(255),
        'Beløb_intern_valuta': Numeric(precision=15, scale=2),
        'Beløb': Numeric(precision=15, scale=2),
        'Betalingsordre': String(255),
        'Bilagsart': String(255),
        'Bilagsdato': Date,
        'Bilagsnummer': String(255),
        'Bilagstype_markering': String(255),
        'BogfDato_udligning': Date,
        'Bogføringsdato': Date,
        'Bortposteringsårsag': String(255),
        'Delposition': Integer,
        'Deltransaktion': String(255),
        'Firmakode': String(255),
        'Forretningspartner': String(255),
        'Henstand_til': Date,
        'Hovedtransaktion': String(255),
        'Indholdsart': String(255),
        'Kommune_kode': String(255),
        'KontofastsætKendet': String(255),
        'Momsindikator': String(255),
        'Nettoforfald': Date,
        'Oprindelse': String(255),
        'Position': Integer,
        'Referencebilagsnr': String(255),
        'Referencenøgle': String(255),
        'Referenceoperation': String(255),
        'Registreringsdato': Date,
        'Rentenøgle': String(255),
        'Rykkeprocedure': String(255),
        'SBS_dokumentnummer': String(255),
        'Skæringsdato': Date,
        'Statistiknøgle': String(255),
        'Tilbageført_via': String(255),
        'Udligningsårsag': String(255),
        'Udligningsbeløb': Numeric(precision=15, scale=2),
        'Udligngningstype': String(255),
        'Udligningsbilag': String(255),
        'Udligningsdato': Date,
        'Udligningsstatus': String(255),
        'Udligningsvaluta': String(255),
        'Valørdato_udligning': Date,
        'Valuta': String(255),
    },

    'Bilag-aaben': {
        'Aftaleindhold': String(255),
        'Aftalekonto': String(255),
        'Aftalekontotype': String(255),
        'Aftalenummer': String(255),
        'Aftalestatus': String(255),
        'Aftaletype': String(255),
        'Antal_poster': Integer,
        'Beløb_intern_valuta': Numeric(precision=15, scale=2),
        'Beløb': Numeric(precision=15, scale=2),
        'BevillAnsvarssted': String(255),
        'Bevillingsposition': String(255),
        'Bevillingsprogram': String(255),
        'Bilagsdato': Date,
        'Bilagsnummer': String(255),
        'Bogføringsdato': Date,
        'Dato-ID': Date,
        'Deltransaktion': String(255),
        'Firmakode': String(255),
        'Forretningspartner': String(255),
        'Funktionsområde': String(255),
        'Henstand_til': Date,
        'Hovedtransaktion': String(255),
        'Identifikation': String(255),
        'Indholdsart': String(255),
        'Kapitalmidler': String(255),
        'Klient': String(255),
        'Kommune_kode': String(255),
        'Kredit_oprindelses_dato': Date,
        'Landenøgle': String(255),
        'Nettoforfald': Date,
        'Original-FI-område': String(255),
        'Periodenøgle': String(255),
        'Position': Integer,
        'Positionstekst': String(255),
        'Postnummer': String(255),
        'Referencebilagsnr': String(255),
        'Registreringsdato': Date,
        'Rykkeniveau': Integer,
        'Rykkeniveautype': String(255),
        'Rykkeprocedure': String(255),
        'Rykkeproceduretype': String(255),
        'SBS_dokumentnummer': String(255),
        'Skæringsdato': Date,
        'Sorteringsbetegnelse': String(255),
        'Statistiknøgle': String(255),
        'Udligning_kredit_oprindelse': String(255),
        'Udligningsstatus': String(255),
        'Valuta': String(255),
    },

    'Bilag-lukket': {
        "Intervalnummer": Integer,
        "Recordnummer": Integer,
        'Afskrivningsårsag': String(255),
        'Afskrivningsdato': Date,
        'Aftaleindhold': String(255),
        'Aftalekonto': String(255),
        'Aftalekontotype': String(255),
        'Aftalenummer': String(255),
        'Aftalestatus': String(255),
        'Aftaletype': String(255),
        'Antal_poster': Integer,
        'Bankafregningskonto': String(255),
        'Beløb_intern_valuta': Numeric(precision=15, scale=2),
        'Beløb': Numeric(precision=15, scale=2),
        'BevillAnsvarssted': String(255),
        'Bevillingsposition': String(255),
        'Bevillingsprogram': String(255),
        'Bilagsdato': Date,
        'Bilagsnummer': String(255),
        'Bilagstype_markering': String(255),
        'BogfDato_udligning': Date,
        'Bogføringsdato': Date,
        'Bortposteringsårsag': String(255),
        'Dato-ID': Date,
        'Deltransaktion': String(255),
        'Firmakode': String(255),
        'Forretningspartner': String(255),
        'Fra': Date,
        'Funktionsområde': String(255),
        'Henstand_til': Date,
        'Hovedtransaktion': String(255),
        'Identifikation': String(255),
        'Indbetalingstype': String(255),
        'Indholdsart': String(255),
        'Kapitalmidler': String(255),
        'Klient': String(255),
        'Kommune_kode': String(255),
        'Kredit_oprindelses_dato': Date,
        'Landenøgle': String(255),
        'Nettoforfald': Date,
        'Original-FI-område': String(255),
        'Position': Integer,
        'Postnummer': String(255),
        'Referencebilagsnr': String(255),
        'Registreringsdato': Date,
        'Rykkeniveau': Integer,
        'Rykkeprocedure': String(255),
        'SBS_dokumentnummer': String(255),
        'Sorteringsbetegnelse': String(255),
        'Statistiknøgle': String(255),
        'Til': Date,
        'Tilbageført_via': String(255),
        'Udligning_kredit_oprindelse': String(255),
        'Udligning': Date,
        'Udligningsårsag': String(255),
        'Udligningsbeløb': Numeric(precision=15, scale=2),
        'Udligningsbilag': String(255),
        'Udligningsdato': Date,
        'Udligningsstatus': String(255),
        'Udligningsvaluta': String(255),
        'Underapplikation': String(255),
        'Valørdato_udligning': Date,
        'Valuta': String(255),
    },

    'Indbetalinger': {
        'Afdeling': String(255),
        'Afklaringsstatus': String(255),
        'Aftale': String(255),
        'Aftalekonto': String(255),
        'Annuller_status': String(255),
        'Art_kilde': String(255),
        'Bankafregningskonto': String(255),
        'Bankforbindelse': String(255),
        'Beløb': Numeric(precision=15, scale=2),
        'Betalings_art': String(255),
        'Betalingsidentifikator': String(255),
        'Betalingsmåde': String(255),
        'Betalingsretning': String(255),
        'Bilagsart': String(255),
        'Firmakode': String(255),
        'Forretningsområde': String(255),
        'Forretningspartner': String(255),
        'Kasse': String(255),
        'Kommune_kode': String(255),
        'Konto-ID': String(255),
        'Langtekst': String(255),
        'Løbenummer': Integer,
        'Oprettet_den': Date,
        'Skæringsdato': Date,
        'Tidsstempel_for_deltaekstrakt': Date,
        'Underapplikation': String(255),
        'Valørdato': Date,
        'Valuta': String(255),
        'Varighed_af_afklaring': Integer,
    },

    'Rykker': {
        'Aftale': String(255),
        'Aftalekonto_ikke_entydig': String(255),
        'Aftalekonto': String(255),
        'Bilagsnummer': String(255),
        'Dato-ID': Date,
        'Delposition': Integer,
        'Firmakode': String(255),
        'Forretningspartner': String(255),
        'Gentagelsesposition': Integer,
        'Identifikation': String(255),
        'Kommune_kode': String(255),
        'Nettoforfald': Date,
        'Nyt_rykkeniveau': Integer,
        'Position': Integer,
        'Printdato': Date,
        'Rentebilag': String(255),
        'Rykkebeløb': Numeric(precision=15, scale=2),
        'Rykkeniveau': Numeric(precision=15, scale=2),
        'Rykkeniveautype': String(255),
        'Rykkeprocedure': String(255),
        'Rykker_annulleret': String(255),
        'Rykkerenter': Numeric(precision=15, scale=2),
        'Rykkertæller': Integer,
        'Rykkespærreårsag': String(255),
        'Segment': String(255),
        'Skæringsdato': Date,
        'Statistiknøgle': String(255),
        'Suspenderings-rykkeniv': String(255),
        'Udskrevet': String(255),
        'Udstedelsesdato': Date,
        'Valuta': String(255),
    },

    'FP-aftale': {
        'AA_type': String(255),
        'Ændret_den': Date,
        'Aftale': String(255),
        'Aftalekonto': String(255),
        'Aftalenummer': String(255),
        'Aftaleposition': Integer,
        'Aftalestatus': String(255),
        'Aftaletype': String(255),
        'Årsag_til_luk_aftale': String(255),
        'Besvaret': Date,
        'Bilagsnummer': String(255),
        'Forretningspartner': String(255),
        'Kommune_kode': String(255),
        'Konvertering': String(255),
        'Lukket_den': Date,
        'Niveau_Aftale_Position': String(255),
        'Oprettet_den': Date,
        'Position': Integer,
        'System_dato': Date,
        'Tilføjelsesdato': Date,
        'UdlBeløb_int_valuta': Numeric(precision=15, scale=2),
        'Valuta': String(255),
    },

    'UU-aftale': {
        'Aftalestatus': String(255),
        'Aftaletype': String(255),
        'Aftalenummer': String(255),
        'Indholdsart': String(255),
        'Aftale': String(255),
        'Aftalekonto': String(255),
        'Deltransaktion': String(255),
        'Bilagsnummer': String(255),
        'Position': Integer,
        'Hovedtransaktion': String(255),
        'Udligningsstatus': String(255),
        'Beløb': Numeric(precision=15, scale=2),
        'Valuta': String(255),
        'Kommune_kode': String(255)
    },

    'UU-aftale-haefter': {
        'Klient': String(255),
        'Aftale': String(255),
        'Aftalekonto': String(255),
        'Aftalenummer': String(255),
        'BetFormReference': String(255),
        'Forretningspartner': String(255),
        'Hovedhæfter': String(255),
        'Hæfter_fjernet': Date,
        'Hæfter_tilføjet': Date,
        'Kommune_kode': String(255)
    },

    'RIM-aftale': {
        'Åbent_beløb_for_perioden': Numeric(precision=15, scale=2),
        'Ændret_den': Date,
        'Ændringsårsagstekst': String(255),
        'Ændringsårsagskode': String(255),
        'Aftalenummer': String(255),
        'Aftalestatus': String(255),
        'Aftaletype': String(255),
        'Afvis': String(255),
        'ActionStatusCode': String(255),
        'Aktionkode': String(255),
        'Aktions-id': Integer,
        'Basisdato_renteberegning': Date,
        'Beløb_accepteret': Numeric(precision=15, scale=2),
        'Beløb': Numeric(precision=15, scale=2),
        'Bilagsnummer': String(255),
        'EFI-nummer': Integer,
        'Forældelsesdato': Date,
        'Forretningspartner': String(255),
        'Kommune_kode': String(255),
        'KravsType': String(255),
        'Krydsende_handling': String(255),
        'Markering_for_tilbagekald': String(255),
        'Medhæfter_status': String(255),
        'Modtagelsesdato': Date,
        'Oprettet_den': Date,
        'Oprettet_kl': String(255),
        'Recall_Amount': Numeric(precision=15, scale=2),
        'Reduceret_beløb': String(255),
        'Reference_til_ændring': String(255),
        'Rest_beløb_markering': String(255),
        'RestBeløb': Numeric(precision=15, scale=2),
        'ReturAarsagKode': String(255),
        'ReturÅrsagText': String(255),
        'Returdato': Date,
        'RIM_ændringsdato': String(255),  # Should be Numeric(precision=15, scale=2), according to documentation. It's a weird value, and not a date.
        'SBS_dokumentnummer': String(255),
        'Slutdato_for_forrentn': Date,
        'Snitflade_Status': String(255),
        'Status': String(255),
        'System_dato': Date,
        'Tilb_Virkningsdato': Date,
        'TilbageAarsagKode': String(255),
        'Trans_Beløb': Numeric(precision=15, scale=2),
        'Trans_flag': String(255),
        'Trans_header_ID': Integer,
        'Trans_sekvens_nr': Integer,
        'Transaktion_identifikator': String(255),
        'Transdato': Date,
        'Transtid': String(255),
        'UdlBeløb_int_valuta': Numeric(precision=15, scale=2),
        'Udligningsdato': Date,
        'UUID': String(255),
        'Valuta': String(255),
        'Valutanøgle': String(255),
        'Virkningsdato': Date,
    },

    'RIM-aftale-rater': {
        'Ændret_den': Date,
        'Aftale': String(255),
        'Aftalekonto': String(255),
        'Aftalekontotype': String(255),
        'Aftalenummer': String(255),
        # 'Aftale_saldo': Numeric(precision=15, scale=2),
        'Aftalestatus': String(255),
        'Aftaletype': String(255),
        'Basisdato_renteberegning': Date,
        'Bilagsnummer': String(255),
        'Creation_Amount': Numeric(precision=15, scale=2),
        'Deltransaktion': String(255),
        'EFI-nummer': Integer,
        'Forældelsesdato': Date,
        'Fordringstype': String(255),
        'Forretningspartner': String(255),
        'Gentagelsesposition': Integer,
        'Henstand_til': Date,
        'Hovedtransaktion': String(255),
        'Indholdsart': String(255),
        'Kommune_kode': String(255),
        'Konvertering_status': String(255),
        'KravsType': String(255),
        'Markering_for_tilbagekald': String(255),
        'Nettoforfald': Date,
        'Oprettet_den': Date,
        'Original_Amount': Numeric(precision=15, scale=2),
        'Position': Integer,
        'Produktionsenh': Integer,
        'Ratespecifikation': String(255),
        'ReturÅrsagText': String(255),
        'ReturAarsagKode': String(255),
        'Returdato': Date,
        'SBS_dokumentnummer': String(255),
        'SBS_Document_Number': String(255),
        'Sidste_rentefrie_indbetalingsdato': String(255),
        'Slettes': String(255),
        'Slutdato_for_forrentn': Date,
        'SRI_dato': Date,
        'Status': String(255),
        'Stiftelsesdato': Date,
        'System_dato': Date,
        # 'System': String(255),
        'Text_Position_Number': Numeric(precision=15, scale=2),
        'Tilb_Virkningsdato': Date,
        'TilbageAarsagKode': String(255),
        'UdlBeløb_int_valuta': Numeric(precision=15, scale=2),
        'Udligningsdato': Date,
        'Valørdato': Date,
        'Valuta': String(255),
        'Ydelsesperiode_fra': Date,
        'Ydelsesperiode_til': Date,
    },

    'RIM-aftale-renter': {
        'Ændret_den': Date,
        'Afklarings_status': String(255),
        'Aftalenummer': String(255),
        'Aftalestatus': String(255),
        'Aftaletype': String(255),
        'Basisdato_renteberegning': Date,
        'EFI-nummer': Integer,
        'Egen_reference': String(255),
        'Forældelsesdato': Date,
        'Fordring_artskode': String(255),
        'Fordring_kategorikode': String(255),
        'Forretningspartner': String(255),
        'Historisk_modtagelsesdato': Date,
        'Hovedfordring_id': Integer,
        'Intr-posnr': Integer,
        'Kommune_kode': String(255),
        'Konvertering_status': String(255),
        'KravsType': String(255),
        'Markering_for_tilbagekald': String(255),
        'Min_beløb_ignoreret': String(255),
        'Modtagelsesdato': Date,
        'Oprettet_den': Date,
        'Oprettet_kl': String(255),
        'Overtagelse_af_inddrivelsesrenter': String(255),
        'P-nummer': Integer,
        'Periodetype_beskrivelse': String(255),
        'Produktionsenh': Integer,
        'Rente,_år_til_dato_beløb,_DKK': Numeric(precision=15, scale=2),
        'Rente,_år_til_dato_beløb': Numeric(precision=15, scale=2),
        'Rentebeløb,_DKK': Numeric(precision=15, scale=2),
        'Rentebeløb': Numeric(precision=15, scale=2),
        'Renteperiode_slut-dato': Date,
        'Renteperiode_start-dato': Date,
        'ReturAarsagKode': String(255),
        'ReturÅrsagText': String(255),
        'Returdato': Date,
        'Slutdato_for_forrentn': Date,
        'System_dato': Date,
        'Tilb_Virkningsdato': Date,
        'TilbageAarsagKode': String(255),
        'Tjek_af_nr_I_Basissystem': String(255),
        'Typekode': String(255),
        'Udledt_fra_betaling': String(255),
        'Udligningsdato': Date,
        'Underretnings-id': Integer,
        'Valuta': String(255),
        'Valutakode': String(255),
    },

    'Forretningspartner': {
        'Klient': String(255),
        'Forretningspartner': String(255),
        'Identifikationsart': String(255),
        # 'Identifikationsnr': String(255),  # Removed, as these often contain CPR
        'Gyldig_fra': Date,
        'Gyldig_til': Date,
        'Datafordeleren_UUID': String(255),
        'Forretningspartner-GUID': String(255),
        'BW_Opdateringsmode': String(255),
        'Slettet': String(255)
    },

    'Aftaleindhold': {
        'Aftaleindhold': String(255),
        'Oprettet_af': String(255),
        'Oprettet_den': Date,
        'Ændret_af': String(255),
        'Ændret_den': Date,
        'Indholdsart': String(255),
        'Bet_aftaleindhold': String(255),
        'Nummer_i_basissystem': String(255),
        'Kommune_kode': String(255)
    },

    'BO-aftale': {
        'Aftalestatus': String(255),
        'Aftaletype': String(255),
        'Aftalenummer': String(255),
        'Bilagsnummer': String(255),
        'Position': Integer,
        'Oprettet_beløb': Numeric(precision=15, scale=2),
        'Valuta': String(255),
        'Første_anmeldelse': Numeric(precision=15, scale=2),
        'Indbetalt_af_bobestyrer': Numeric(precision=15, scale=2),
        'Fjernet': String(255),
        'Bobehandling': String(255),
        'Indholdsart': String(255),
        'Deltransaktion': String(255),
        'Hovedtransaktion': String(255),
        'Aftalekonto': String(255),
        'Aftale': String(255),
        'Kommune_kode': String(255),
        'Restbeløb': Numeric(precision=15, scale=2),
        'Afskrevet': Numeric(precision=15, scale=2),
        'Ændringer_efter_første_anmeld': Numeric(precision=15, scale=2)
    },

    'BO-aftale-haendelse': {
        'Klient': String(255),
        'Aftalenummer': String(255),
        'Bobehandling': String(255),
        'Ekstern_reference_nøgle': String(255),
        'Udtrækstype': String(255),
        'Korrespondanceart': String(255),
        'Printdato': Date,
        'Afskrevet': Numeric(precision=15, scale=2),
        'Afskrivnings_dato': Date,
        'Betalingsdato': Date,
        'Valuta': String(255),
        'Kommune_kode': String(255),
        'Beløb': Numeric(precision=15, scale=2),
        'Indbetalt_af_bobestyrer': String(255),
    },

    'Opsaetning-Aftalekontotype': {
        'Klient': Numeric(precision=15, scale=2),
        'Sprognøgle': String(255),
        'Aftalekontotype': String(255),
        'Kontotype_tekst': String(255)
    },

    'Opsaetning-Rykkerniveau': {
        'Sprognøgle': String(255),
        'Rykkeprocedure': String(255),
        'Rykkeniveau': Integer,
        'Betegnelse': String(255),
        'Kommune_kode': String(255)
    }
}
